# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: deploy gallery

on:
  push:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node 16
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Build
      run: |
          cd app
          npm ci
          npm run build --if-present
    - name: Deploy app to gh-pages
      if: True
      uses: JamesIves/github-pages-deploy-action@4.1.2
      with:
        branch: gh-pages
        folder: app/build
